version: '3.7'

services:

  user-service:
    build: ./user-service
    container_name: user-service_debug
    ports:
      - "8081:8081"
      - "5005:5005"  
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
      - spring.config.import=optional:configserver:http://config-server:8888
    command: mvn spring-boot:run -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
    depends_on:
      config-server: 
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      user-db:
        condition: service_healthy

  email-service:
    build: ./email-service
    container_name: email-service_debug
    ports:
      - "8082:8082"
      - "5006:5006"  
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
      - spring.config.import=optional:configserver:http://config-server:8888
    command: mvn spring-boot:run -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5006"
    depends_on:
      config-server: 
        condition: service_healthy
      eureka-server:
        condition: service_healthy